### ISSUE TITLE
Pretty good, but...

### ISSUE THREAD

**Issue by vgedrovits-mwb** [matheusguermandi/coderbyte-project#1]
Pretty good, but there is no communication between browser windows and the products list doesn't sync between different users.

1. How would you handle centralized Products inventory, so the removal of the products synced between 2 different sessions?
2. Communication between windows, so when the User 1 changed quantity, User 2 is also notified about that?

**Comment by matheusguermandi** [comment]
Hello @vgedrovits-mwb, I agree with your observation that these features in question has not been implemented yet.

Currently, my focus is on handling the interaction of a single user. However, I'm aware that as the application scales up to support multiple users, I will need to handle events and notifications related to them.

To address this, I plan to delegate this responsibility to the server side. This means that the server will be responsible for handling events and notifications related to multiple users, while the client side will be notified using socket technology.

This approach will ensure that the server can handle large amounts of data and requests from multiple users, without impacting the performance of the client side. 

Let me know if you have any further questions or suggestions. :)

**Comment by matheusguermandi** [comment]
Hello @vgedrovits-mwb, I agree with your observation that these features in question has not been implemented yet.

Currently, my focus is on handling the interaction of a single user. However, I'm aware that as the application scales up to support multiple users, I will need to handle events and notifications related to them.

To address this, I plan to delegate this responsibility to the server side. This means that the server will be responsible for handling events and notifications related to multiple users, while the client side will be notified using socket technology.

This approach will ensure that the server can handle large amounts of data and requests from multiple users, without impacting the performance of the client side.

Let me know if you have any further questions or suggestions. :)

**Comment by matheusguermandi** [comment]
Hello @vgedrovits-mwb , I hope you're doing well. I wanted to share with you some recent progress on the project. Over the past week, I had a few opportunities to work on the project and I am excited to share a new PR that includes some significant improvements. You can find the PR at https://github.com/matheusguermandi/coderbyte-project/pull/2.

With these improvements, the project now has a more robust cart management system, as all cart logic has been moved to the backend. Additionally, I have implemented socket communication, which notifies users when one user close their cart.

I would appreciate it if you could take some time to review the PR and provide any feedback or suggestions. Thank you!
